name: ESP-IDF

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    container:
      image: "espressif/idf:v5.3"
    steps:
      - uses: actions/checkout@v4
      - run: |
          . $IDF_PATH/export.sh
          idf_tools.py install esp-clang
          . $IDF_PATH/export.sh
          which clang-format
          make format-check

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - v5.3
        target:
          - esp32s3
        example:
          - examples/esp_idf
        include:
          - version: v5.3
            example: jpeg_demo
          - version: v5.3
            example: papers3_demo

    continue-on-error: ${{ matrix.version == 'latest' }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: 'espressif/esp-idf-ci-action@main'
        with:
          esp_idf_version: ${{ matrix.version }}
          target: ${{ matrix.target }}
          path: 'examples/${{ matrix.example }}'

  build-arduino:
    runs-on: ubuntu-latest
    container:
      image: "espressif/idf:${{ matrix.version }}"
    strategy:
      fail-fast: false
      matrix:
        version:
          - release-v5.3
        example:
          - Arduino/show_jpeg
        arduino-esp32: 
          - 3.1.3 

    steps:
      - name: Install latest git
        run: |
          apt update -qq && apt install -y -qq git
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Arduino ESP
        run: |
          cd examples/${{ matrix.example }}
          mkdir components && cd components
          git clone --depth 1 --recursive --branch ${{ matrix.arduino-esp32 }} https://github.com/espressif/arduino-esp32.git arduino
      - name: esp-idf build
        run: |
          . $IDF_PATH/export.sh
          cd examples/${{ matrix.example }}
          idf.py build

